### PR TITLE
Pin to libnetcdf 4.4

### PR DESCRIPTION
**Pull request by ocefpaf**
Needs https://github.com/conda-forge/libnetcdf-feedstock/pull/1.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Linux failure is puzzling to me:

```shell
/feedstock_root/build_artefacts/work/nco-4.6.0/autobld/missing: /opt/conda/envs/_build/bin/makeinfo: /usr/bin/perl: bad interpreter: No such file or directory
```

Does this means we need to add `perl` as a build dependency on the new docker image?

**Comment by kmuehlbauer** [comment]
@ocefpaf Been there, done that :sob: https://github.com/conda-forge/netcdf-cxx4-feedstock/pull/9 

Is there something that changed recently?

**Comment by ocefpaf** [comment]
> Is there something that changed recently?

Still investigating... But if `perl` is no longer available in the docker image we need to figure out which build tool(s) need it and fix them. (Here I suspect `texinfo`, but I am heading out to a meeting so it won't be able to take a better look at this.)

**Comment by ocefpaf** [comment]
@kmuehlbauer adding `perl` to `texinfo` solved it here. Going to `netcdf-cxx4` case now.

**Pull request merged**
