### PR TITLE
Add arm64, aarch64 and ppc64le builds

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
#164 was not successful.  I don't know what happened that I merged it.  I think maybe I saw it before CI even started and thought it had run successfully.

Anyway, `antlr >=2.7.7,<3` seems to be the problem (or at least the first one).  The oldest version of OSX-ARM64 support on conda-forge is 4.9.2.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
As expected, the aarch64 and ppc64le builds fail with the same `antlr` issue.  They require an even newer build.

I looked into rebuilding `antlr` 2.7.7 for these architectures but it seems like a lot of work with little chance of success for a very old package.

**Comment by czender** [comment]
Thanks for finding and confirming that missing Antlr 2.7.7 package is the problem for the newer architectures. I will need to figure out how to update the Antlr 2.7.7 feedstock. Unfortynately, Antlr v3+ has a completely different, non back-compatible  API and cannot be used as is.

**Comment by xylar** [comment]
Oh, boy. Okay, that's going to be a project but I can make a PR for us to start from.

**Comment by zklaus** [comment]
With conda-forge/antlr-feedstock#53 merged, we should give this another try in a couple of hours.

**Comment by zklaus** [comment]
@conda-forge-admin, please restart ci

**Comment by xylar** [comment]
@zklaus and @czender, in all 3 failing cases, we're seeing:
```
########################################
#     Testing for GSL support          #
########################################
configure: These GSL library and header tests must succeed for GSL support:
checking for gsl_sf_gamma_inc in -lgsl... yes
configure: error: cannot check for file existence when cross compiling
```
Any thoughts?

**Comment by xylar** [comment]
@zklaus, I just invited you to collaborate on my fork.  Once you accept, I think you should be able to push to this (poorly named) branch.  @czender, feel free to push to this branch, too.

**Comment by zklaus** [comment]
Thanks, @xylar, I am on board now. This is the usual cross compiling territory: Many all autotools checks that rely on running a snippet of code don't work because the compiler produces code for arm, but the build is running on x86. To address this, the easiest way is to provide the result of these tests as cached variables in the build script (c.f. [hdf5 example, l54ff](https://github.com/conda-forge/hdf5-feedstock/blob/15df8dfc7e056f45a1661e7b01eafb0a6e642b95/recipe/build.sh#L54). The work now is to figure out which variables are needed and what values they should have.

A quick grep for the error message in the configure script shows the following occurrences:
```bash
20805:  as_fn_error $? "cannot check for file existence when cross compiling" "$LINENO" 5
21203:  as_fn_error $? "cannot check for file existence when cross compiling" "$LINENO" 5
21229:  as_fn_error $? "cannot check for file existence when cross compiling" "$LINENO" 5
21250:  as_fn_error $? "cannot check for file existence when cross compiling" "$LINENO" 5
21271:  as_fn_error $? "cannot check for file existence when cross compiling" "$LINENO" 5
21301:  as_fn_error $? "cannot check for file existence when cross compiling" "$LINENO" 5
21323:  as_fn_error $? "cannot check for file existence when cross compiling" "$LINENO" 5
21344:  as_fn_error $? "cannot check for file existence when cross compiling" "$LINENO" 5
21380:  as_fn_error $? "cannot check for file existence when cross compiling" "$LINENO" 5
21459:  as_fn_error $? "cannot check for file existence when cross compiling" "$LINENO" 5
```

What makes this build extra fun is that the variable names are determined dynamically, depending on the include path for gsl (and possibly other dependencies after that).

**Comment by czender** [comment]
Thanks for all the help and hints @xylar and @zklaus. It looks like the failed builds now make it past GSL only to break in the UDUnits section. That `configure.ac` code is pretty crufty! I am looking to see what can be eliminated in light of the constraint introduced by cross-compiling that file existence cannot be tested for...

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
> Thanks for all the help and hints @xylar and @zklaus. It looks like the failed builds now make it past GSL only to break in the UDUnits section. That `configure.ac` code is pretty crufty! I am looking to see what can be eliminated in light of the constraint introduced by cross-compiling that file existence cannot be tested for...

Cheers, @czender. I think probably the `export UDUNITS2_PATH` is enough to get us past the udunits bits, but it is difficult to pinpoint which line in `configure` is triggering the error from the output alone. I have now activated the storage of artifacts, which will give us access to the `configure.log` with line numbers, which should make the process a bit more straightforward, albeit also more iterative.

Simplifying `configure.ac` is overall a good idea, I think, unless you want to jump straight to Cmake or Meson :smirk:

**Comment by czender** [comment]
I just tagged a new NCO snapshot 5.1.4-alpha05 which has a simplified configure.ac to avoid the previous cross-compilation issues encountered searching for UDUnits:
```
zender@spectral:~/Downloads$ openssl dgst -sha256 nco-5.1.4-alpha05.tar.gz 
SHA256(nco-5.1.4-alpha05.tar.gz)= d9817ba132940cc618e7b25b059a14f98b883be4c4e0e9ceb5fc0a02b1df0836
```

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@zklaus, I couldn't possibly have done what you did here. Thanks a ton!

@czender and @zklaus, as long as you're both happy, let's merge this!

**Comment by czender** [comment]
Moi, je suis ecstatic!

**Comment by zklaus** [comment]
Donc, c'est parti!
Happy to simplify particularly the UDUNITS part when we move to 1.5.4.
I am not a maintainer here, so I cannot merge, but please go ahead :+1:

**Comment by xylar** [comment]
Thank you again!

**Comment by ocefpaf** [comment]
Thanks all involved and specially @zklaus for getting it ready to be merged!

**Pull request merged**
