### PR TITLE
Rebuild for hdf5=1.10.4

### PR DESCRIPTION
**Pull request by xylar**
My group has packages outside of conda-forge that aren't ready for hdf5=1.10.5 :-(  To accommodate this, I need another build with the older version of hdf5.  This is being merged to a different branch so the recipe on `master` doesn't get updated.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@ocefpaf, what should I use for a build number in this case?  I'm concerned that if I use 1, there could be confusion since `master` won't get updated with the new build number.  I think we've used 100 or something like that in the past.

Also, I apologize on behalf of those on my project who can't be bothered to keep up with package versions supported on conda-forge.

**Comment by xylar** [comment]
I'm going to go ahead and merge with build number 100.  @ocefpaf, if that's a problem, please let me know so I don't make the same mistake in the future.

**Comment by ocefpaf** [comment]
That is fine. Sorry for the delay. (At SciPy this week.)

**Pull request merged**
