### PR TITLE
Update to NCO 4.7.2

### PR DESCRIPTION
**Pull request by xylar**
see release: https://github.com/nco/nco/releases/tag/4.7.2

### CODE REVIEW

**Comment by xylar** [comment]
@pedro-vicente, I get the sense you have some expertise on the Windows side.  Care to take a look at what's going wrong with the AppVeyor build?  I couldn't make heads or tails of the output.

**Comment by pedro-vicente** [comment]
I replaced the name of the option
 NCO_MSVC_USE_MT
to
MSVC_USE_STATIC_CRT

to keep it consistent with the name used by the other libraries

there are 2 new scripts in /cmake
 clone.bat
git clones all the depencies
bld.bat

builds NCO

you can the bld.bat for the CMake options used

blb.bat crt

with crt as option builds static CRT version (Debug Win64)

**Comment by ocefpaf** [comment]
Thanks @xylar!

@pedro-vicente if I got your https://github.com/conda-forge/nco-feedstock/pull/57#issuecomment-360636405 we need to change [this line](https://github.com/conda-forge/nco-feedstock/blob/master/recipe/bld.bat#L10) from,

```bat
-D NCO_MSVC_USE_MT=no ^
```

to 

```bat
-D MSVC_USE_STATIC_CRT=OFF ^
```

correct?

**Comment by pedro-vicente** [comment]
yes, simple fix

**Comment by xylar** [comment]
Okay, great, I can take care of that.

**Comment by xylar** [comment]
@pedro-vicente, could you check if 3868b76 is what you wanted? Thanks!

**Comment by xylar** [comment]
Hmm, looks like that wasn't enough on its own.  @pedro-vicente, please let me know if you have additional changes you would suggest.

**Comment by isuruf** [comment]
Changes at https://github.com/nco/nco/commit/7091248e8fc4a21ddaef31f8c9dac7c0656ba64f#diff-a127e43c07e7f91eafc26afd2cd0c9deL29 needs to be reverted

**Comment by xylar** [comment]
@isuruf, okay, I think this should probably be submitted to the NCO git repo as an issue.

**Comment by pedro-vicente** [comment]
MSVC does not define strcasecmp; so we use 

`# define NEED_STRCASECMP` 

I would like to avoid the 

`define strncasecmp _strnicmp`

solution if possible

**Comment by pedro-vicente** [comment]
errors/warning are

```
e:\nco\src\nco\nco_sng_utl.h(63): warning C4273: '_stricmp': inconsistent dll linkage [E:\nco\cmake\nco.vcxproj]
ucrtd.lib(ucrtbased.dll) : error LNK2005: _stricmp already defined in nco.lib(nco_sng_utl.obj) [E:\nco\cmake\ncbo.vcxproj]
```
https://docs.microsoft.com/en-us/cpp/c-runtime-library/crt-library-features

**Comment by pedro-vicente** [comment]
I defined the workaround in the Cmake script until the root cause of the error is found

https://github.com/nco/nco/commit/4e5e769132527fa440711e7d6c80b989a743c45d

you should have no errorrs in your build now

**Comment by czender** [comment]
Thank you @xylar @isuruf and @pedro-vicente for looking into this breakage, which seemed to  become known only after the 4.7.2 release. I have a meta-question: I made many tags after the offending commit and prior to releasing 4.7.2, yet I did not notice AppVeyor CI sending me any messages about breakage. Travis CI tests and sends me a report after every tag, but apparently AppVeyor does not. How or can we make it so AppVeyor tests and sends me (and Pedro too, I think) results after each tag?

**Comment by isuruf** [comment]
@czender, you can go to https://ci.appveyor.com/project/czender/nco/settings/notifications and add a list of emails that you want to notify.

**Comment by czender** [comment]
Thanks @isuruf. AppVeyor has a zillion options, almost none of which were set. I modified to run AppVeyor on every new NCO tag, and to send success and failure notifications via email to me and @pedro-vicente. That should prevent us from being surprised at release time :)

**Comment by xylar** [comment]
@czender, and others, how do we want to handle this?  Should we go ahead and merge this PR once we know whether the OSX version is working (but without a working Windows version)?  Then, once AppVeyor is working as expected on the NCO repo maybe have another release so we can also update the Windows version?  Or is there another suggestion for how to proceed?

**Comment by ocefpaf** [comment]
@xylar merging this and opening an issue for Windows is fine, actually I would not even wait for Travis-CI b/c the backlog is ridiculously long due to some incidents upstream and we don't want to wait weeks to merge this.

**Comment by xylar** [comment]
> I recommend using PRs to incrementally make code changes

I agree this would probably be more helpful than the current NCO practice of committing to master.  I realize this would be a significant change in repo management style...

**Comment by xylar** [comment]
Thanks @ocefpaf for merging this and for the helpful comments.

**Comment by pedro-vicente** [comment]
I am lost here in the list of issues... are there any Windows build failures?

if you do a git pull from NCO and build there should be no errors... I tried the /cmake/bld.bat with CRT to OFF and it built fine

**Comment by pedro-vicente** [comment]
this is what /cmake/bld.bat uses

there are 2 new options that you can add to your scripts, if you want less verbose output/warnings

```
 -DMSVC_DEVELOPER=ON ^
  -DCMAKE_VERBOSE_MAKEFILE:BOOL=OFF ^
```


```

 cmake .. -G %MSVC_VERSION% ^
  -DMSVC_DEVELOPER=ON ^
  -DCMAKE_VERBOSE_MAKEFILE:BOOL=OFF ^
  -DMSVC_USE_STATIC_CRT=%STATIC_CRT% ^
  -DNETCDF_INCLUDE:PATH=%root%/netcdf-c/include ^
  -DNETCDF_LIBRARY:FILE=%root%/netcdf-c/build/liblib/Debug/netcdf.lib ^
  -DHDF5_LIBRARY:FILE=%root%/hdf5/build/bin/Debug/libhdf5_D.lib ^
  -DHDF5_HL_LIBRARY:FILE=%root%/hdf5/build/bin/Debug/libhdf5_hl_D.lib ^
  -DZLIB_LIBRARY:FILE=%root%/zlib/build/Debug/zlibstaticd.lib ^
  -DSZIP_LIBRARY:FILE=%root%/szip/build/bin/Debug/libszip_D.lib ^
  -DCURL_LIBRARY:FILE=%root%/curl/builds/libcurl-vc14-x64-debug-static-ipv6-sspi-winssl/lib/libcurl_a_debug.lib ^
  -DUDUNITS2_INCLUDE:PATH=%root%/UDUNITS-2/lib ^
  -DUDUNITS2_LIBRARY:FILE=%root%/UDUNITS-2/build/lib/Debug/udunits2.lib ^
  -DEXPAT_LIBRARY:FILE=%root%/libexpat/expat/build/Debug/expatd.lib ^
  -DGSL_INCLUDE:PATH=%root%/gsl/build ^
  -DGSL_LIBRARY:FILE=%root%/gsl/build/Debug/gsl.lib ^
  -DGSL_CBLAS_LIBRARY:FILE=%root%/gsl/build/Debug/gslcblas.lib ^
  -DANTLR_INCLUDE:PATH=%root%/antlr2/lib/cpp ^
  -DANTLR_LIBRARY:FILE=%root%/antlr2/lib/cpp/build/Debug/antlr.lib 
  msbuild nco.sln /target:build /property:configuration=debug
```

**Comment by isuruf** [comment]
@pedro-vicente, problem is that the 4.7.2 release doesn't have your latest patch. conda-forge is building off the source tarball, and it needs to be patched to allow a windows build

**Comment by pedro-vicente** [comment]
@isuruf 
got it :-)

but can you do a manual pull and build from the current version?

**Comment by ocefpaf** [comment]
> but can you do a manual pull and build from the current version?

@pedro-vicente we really prefer to build from released versions instead of latest master. Otherwise we are doomed to provide endless continuous builds. All users like some stability :wink:

**Comment by xylar** [comment]
@pedro-vicente, I think we're going to have to wait until the next NCO release to fix this problem on conda-forge.

**Comment by pedro-vicente** [comment]
@czender 

I found out the mystery about the _stricmp errors below

UDUNITS also defines strcasecmp, and this caused this error


```
e:\nco\src\nco\nco_sng_utl.h(63): warning C4273: '_stricmp': inconsistent dll linkage [E:\nco\cmake\nco.vcxproj]
ucrtd.lib(ucrtbased.dll) : error LNK2005: _stricmp already defined in nco.lib(nco_sng_utl.obj) [E:\nco\cmake\ncbo.vcxproj]
```

solution : detect UDUNITS in Cmake and use 2 definitions for strcasecmp AND strncasecmp

**Comment by pedro-vicente** [comment]
```

if (UDUNITS2_LIBRARY AND UDUNITS2_INCLUDE)
 set(have_udunits)
endif()

if (MSVC)
 if (NOT ${have_udunits})
   add_definitions(-DNEED_STRCASECMP)
 endif()
 add_definitions(-DNEED_STRNCASECMP)
endif(MSVC)
```

**Comment by pedro-vicente** [comment]
@ocefpaf and all

the reason we don't use 

`-Dstrncasecmp=_strnicmp`

is because they are 2 different functions , that just happen to do the same thing;
since NCO defines an internal 'strncasecmp' for cases when it does not exist (like in MSVC)
it's better to use that; also it seems the 
duplicate definition has a different use of dllimport (warning C4273: '_stricmp': inconsistent dll linkage)

**Pull request merged**
