### PR TITLE
Update to 4.9.9

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

I'm going to do a first build with `libnetcdf` 4.8.0 in case anyone needs it, then update to 4.8.0 in another PR.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@czender, could you have a look.  Keep in mind what I wrote above.  `libnetcdf` 4.8.0 will come as soon as this is done.

**Comment by czender** [comment]
@xylar yes, you included the changes I would like to have in `meta.yaml`.

**Comment by xylar** [comment]
I'm going to take my chances that Win will also build, demonstrate my hubris and add the "automerge" label.

**Comment by xylar** [comment]
Thanks, @czender, this work is all on you!

**Pull request merged**
