### PR TITLE
Try win

### PR DESCRIPTION
**Pull request by ocefpaf**
Testing the Windows `cmake` file.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@gillins could you take a look at this Windows build? (This not a priority and I know you are quite busy, there is no rush.)

**Comment by gillins** [comment]
Seems VC still uses `__restrict` rather than C99's `restrict`. I wonder if adding:
```
-D CMAKE_C_FLAGS="-Drestrict=__restrict"
```
Might workaround this?

**Comment by ocefpaf** [comment]
With https://github.com/conda-forge/nco-feedstock/pull/28/commits/9aa8d7197f42a3e631875908ad18926c39dd8337 the failures are different :smile: but still alien to me.

At the end we get `fatal error C1003: error count exceeds 100; stopping compilation`. I am not sure if those errors are something that we should fix in the code or if there is some flag to ignore them.

```shell
Scanning dependencies of target ncks
[  1%] Building C object CMakeFiles/ncks.dir/src/nco/ncks.c.obj
ncks.c
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\stdlib.h(599) : error C2485: '__restrict' : unrecognized extended attribute
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\stdlib.h(601) : error C2485: '__restrict' : unrecognized extended attribute
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\stdlib.h(602) : error C2485: '__restrict' : unrecognized extended attribute
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\stdlib.h(603) : error C2485: '__restrict' : unrecognized extended attribute
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\stdlib.h(605) : error C2485: '__restrict' : unrecognized extended attribute
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\stdlib.h(606) : error C2485: '__restrict' : unrecognized extended attribute
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\stdlib.h(607) : error C2485: '__restrict' : unrecognized extended attribute
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\stdlib.h(608) : error C2485: '__restrict' : unrecognized extended attribute
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\stdlib.h(609) : error C2485: '__restrict' : unrecognized extended attribute
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\stdlib.h(610) : error C2485: '__restrict' : unrecognized extended attribute
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\math.h(624) : warning C4005: 'M_LN2' : macro redefinition
        c:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\nco.h(99) : see previous definition of 'M_LN2'
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\math.h(625) : warning C4005: 'M_LN10' : macro redefinition
        c:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\nco.h(96) : see previous definition of 'M_LN10'
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\math.h(626) : warning C4005: 'M_PI' : macro redefinition
        c:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\nco.h(102) : see previous definition of 'M_PI'
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\INCLUDE\math.h(627) : warning C4005: 'M_PI_2' : macro redefinition
        c:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\nco.h(105) : see previous definition of 'M_PI_2'
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(168) : error C2059: syntax error : '.'
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1091) : error C2143: syntax error : missing ';' before 'type'
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1092) : error C2065: 'PCK_ATT_CPY' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1184) : error C2275: 'prn_fmt_sct' : illegal use of this type as an expression
        c:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\nco.h(977) : see declaration of 'prn_fmt_sct'
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1184) : error C2146: syntax error : missing ';' before identifier 'prn_flg'
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1184) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1185) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1185) : error C2224: left of '.cdl' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1186) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1186) : error C2224: left of '.jsn' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1187) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1187) : error C2224: left of '.srm' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1188) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1188) : error C2224: left of '.xml' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1189) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1189) : error C2224: left of '.trd' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1190) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1190) : error C2224: left of '.cdl' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1190) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1190) : error C2224: left of '.xml' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1190) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1190) : error C2224: left of '.nfo_xtr' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1190) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1190) : error C2224: left of '.nfo_xtr' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1191) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1191) : error C2224: left of '.new_fmt' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1192) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1192) : error C2224: left of '.hdn' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1193) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1193) : error C2224: left of '.rad' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1195) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1195) : error C2224: left of '.cdl' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1195) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1195) : error C2224: left of '.xml' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1201) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1201) : error C2224: left of '.fl_stb' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1204) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1204) : error C2224: left of '.xml' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1204) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1204) : error C2224: left of '.jsn' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1204) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1204) : error C2224: left of '.fl_in' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1205) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1205) : error C2224: left of '.spr_nmr' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1206) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1206) : error C2224: left of '.spr_chr' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1207) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1207) : error C2224: left of '.xml_lcn' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1208) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1208) : error C2224: left of '.gpe' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1209) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1209) : error C2224: left of '.md5' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1210) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1210) : error C2224: left of '.ndn' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1211) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1211) : error C2224: left of '.spc_per_lvl' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1212) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1212) : error C2224: left of '.sxn_fst' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1213) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1213) : error C2224: left of '.var_fst' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1214) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1214) : error C2224: left of '.tab' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1215) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1215) : error C2224: left of '.nbr_zro' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1216) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1216) : error C2224: left of '.fll_pth' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1216) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1216) : error C2224: left of '.fll_pth' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1217) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1217) : error C2224: left of '.xml' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1217) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1217) : error C2224: left of '.nwl_pst_val' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1217) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1217) : error C2224: left of '.nwl_pst_val' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1218) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1218) : error C2224: left of '.dlm_sng' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1219) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1219) : error C2224: left of '.ALPHA_BY_FULL_GROUP' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1220) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1220) : error C2224: left of '.ALPHA_BY_STUB_GROUP' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1221) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1221) : error C2224: left of '.FORTRAN_IDX_CNV' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1222) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1222) : error C2224: left of '.PRN_DMN_IDX_CRD_VAL' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1223) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1223) : error C2224: left of '.PRN_DMN_UNITS' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1224) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1224) : error C2224: left of '.PRN_DMN_VAR_NM' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1225) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1225) : error C2224: left of '.PRN_GLB_METADATA' must have struct/union type
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1226) : error C2065: 'prn_flg' : undeclared identifier
C:\bld\nco_1486916168258\work\nco-4.6.4\src\nco\ncks.c(1226) : fatal error C1003: error count exceeds 100; stopping compilation
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~1.0\VC\bin\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
(C:\bld\nco_1486916168258\_b_env) C:\bld\nco_1486916168258\work\nco-4.6.4\build>if errorlevel 1 exit 1 
```

**Comment by gillins** [comment]
I think a lot of those later errors will go away when we fix the first ones. 

With the py27 errors - I see that my __restrict hack has broken the system headers... That nco.h file may need patching to replace `restrict` with `__restrict`.

I see that py35 is getting a lot further but is falling over with [C2055](https://msdn.microsoft.com/en-us/library/w8s382kk.aspx) on nco_fl_utl.c line 260. Maybe adding a var name to the parameter (eg `char * nco_fl_info_get(const char *bob){return NULL;}`) will fix that?

I'm going on leave for a few weeks (same as you I think) but will look into it more in early March if it isn't resolved by then. It seems like this package hasn't seen much testing on Windows....

**Comment by ocefpaf** [comment]
> I'm going on leave for a few weeks (same as you I think)

Yes. I will be out for a few weeks.

> but will look into it more in early March if it isn't resolved by then.

Thanks @gillins I really appreciate that but I will try the patching you mentioned above.

> It seems like this package hasn't seen much testing on Windows....

I guess that only @pedro-vicente had success building `nco` on Windows. (I was hoping for Windows 10+bash to save us :wink:)

**Comment by gillins** [comment]
Hi @ocefpaf I've also been looking into this, seems that there a whole bunch of things here that aren't working on MSVC (and especially MSVC2008). Might need upstream to make some changes to accommodate VC better before doing more with this...

**Comment by ocefpaf** [comment]
> Hi @ocefpaf I've also been looking into this, seems that there a whole bunch of things here that aren't working on MSVC (and especially MSVC2008). Might need upstream to make some changes to accommodate VC better before doing more with this...

I agree. I don't have the knowledge nor the time to complete this task. @pedro-vicente is the only one that had success building this but, if we cannot reproduce it in our CIs, we cannot use it for `conda-forge`.

**Comment by pedro-vicente** [comment]
I just tried right now , the cmake builkd runs fine...
however I get the same compiler errors..
hmm, not really sure why I did not get them before

but there is a fix :-)

NCO code is  C99, and Visual Studio does not handle it well ... so the fix is to compile as C++

right now, just open the generated projects , right click on project name, go
to tab C/C++ / Advanced and set

Compile as C++ Code (/TP)

Thanks to Charlie for noticing this in the first place

this should be possible to set in the CMake script, I'll do that soon

regarding the dependencies

open CMakeLists.txt

at the top there are comments with the paths/libraries you have to set up at command line

#NETCDF_INCLUDE
#NETCDF_LIBRARY
#HDF5_LIBRARY
#HDF5_LIBRARY
#HDF5_HL_LIBRARY
#ZLIB_LIBRARY
#SZIP_LIBRARY
#CURL_LIBRARY

I just tried for Visual Studio 2015 with my local paths (should work with 2013, 2012, 2010)..

or you can go ahead and try the new 2017, just released yesterday

K:\nco\build>cmake .. -G "Visual Studio 14" -DNETCDF_INCLUDE=L:\grafic_project\netcdf\include -DNETCDF_LIBRARY=L:\grafic_project\Debug\netcdf.lib -DHDF5_LIBR
ARY=L:\grafic_project\Debug\hdf5.1.8.5.patch1.lib -DHDF5_HL_LIBRARY=L:\grafic_project\Debug\hdf5_hl.1.8.5.patch1.lib -DZLIB_LIBRARY=L:\grafic_project\Debug\z
lib.lib -DSZIP_LIBRARY=L:\grafic_project\Debug\szlib.lib -DCURL_LIBRARY=L:\grafic_project\Debug\libcurld.lib
-- The C compiler identification is MSVC 19.0.24213.1
-- The CXX compiler identification is MSVC 19.0.24213.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found netcdf.h header file at: L:/grafic_project/netcdf/include
-- Found netcdf library at: L:/grafic_project/Debug/netcdf.lib
-- Found hdf5 library at: L:/grafic_project/Debug/hdf5.1.8.5.patch1.lib
-- Found hdf5 high level library at: L:/grafic_project/Debug/hdf5_hl.1.8.5.patch1.lib
-- Found zlib library at: L:/grafic_project/Debug/zlib.lib
-- Found szip library at: L:/grafic_project/Debug/szlib.lib
-- Found curl library at: L:/grafic_project/Debug/libcurld.lib
-- Configuring done
-- Generating done
-- Build files have been written to: K:/nco/build


At the moment there are some NCO build errors, but that is just because this is recent changes 

K:\nco\src\nco\nco_mta.c(32): error C3861: 'strsep': identifier not found


>>> there a whole bunch of things here that aren't working on MSVC (and especially MSVC2008).

I doubt that using MSVC2008 will ever work... the compiler is 10 years old :-)

**Comment by pedro-vicente** [comment]
regarding the SZIP dependency
if your HDF5 does not link with SZIP, just comment or delete the detection in CMakeLists.txt

find_library(SZIP_LIBRARY NAMES sz)
if(NOT SZIP_LIBRARY)
  message(FATAL_ERROR "szip library not found")
else()
  message("-- Found szip library at: " ${SZIP_LIBRARY})
endif()

**Comment by ocefpaf** [comment]
> regarding the SZIP dependency

That is already done in this PR. See https://github.com/conda-forge/nco-feedstock/pull/28/commits/e76fa6e94896cde3a754b1b697b8c43d3767a93a

It would be nice if the build script did not enforce `szip` though. It could be set via a variable or something to make the script more friendly to a generic build.

> right now, just open the generated projects , right click on project name, go
to tab C/C++ / Advanced and set
Compile as C++ Code (/TP)
Thanks to Charlie for noticing this in the first place
this should be possible to set in the CMake script, I'll do that soon

Changing the CMake script to reflect that is probably the best course of action for us. We do automated builds on AppVeyor and we cannot do any manual edits to the project like that unless patch, like we did for `szip`, but I guess this seems like an improvement that should go into the build script upstream.

**Comment by pedro-vicente** [comment]
@ocefpaf 

>>> Changing the CMake script to reflect that is probably the best course of action for us. 

I'll change this today and also the SZIP issue

**Comment by pedro-vicente** [comment]
I pushed the  Cmake script changes that makes the build as C++ for Visual Studio

**Comment by pedro-vicente** [comment]
and also this option
-DFIND_SZIP:BOOL=OFF

to disable SZIP detection

**Pull request closed without merging**
